# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27a13eda866469196a5144012a503521177a2860654a93c675e8760ac9e58c10479536bba6ac75da0865c5dca341bace12d2b168935bb9e46ee82aac5dffaedd

test:
  secret_key_base: 60b004465bcf931f1d0f7f6f698989a18e3ec55d2ddb9837bde43f4b292cd57c56f272e6f1e963d57c1f538efb21ee2514e3f086cdde72c8be2c6804162e1eaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
